-- ArcticBlue Event Opportunity rebuild (additive, review before applying)
-- This migration intentionally does NOT delete or rewrite manual_events/event_state.

create table if not exists public.event_candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date,
  end_date date,
  city text,
  country text,
  region text,
  url text,
  source_url text,
  source_name text,
  about text,
  audience_summary text,
  speaking_route text,
  apply_url text,
  deadline date,
  status text not null default 'candidate' check (status in ('candidate','promoted','rejected','expired')),
  rejection_reason text,
  fingerprint text,
  discovered_by text,
  discovered_at timestamptz not null default now(),
  last_verified_at timestamptz,
  raw_research jsonb not null default '{}'::jsonb
);
create index if not exists event_candidates_dates_idx on public.event_candidates(start_date,end_date);
create index if not exists event_candidates_status_idx on public.event_candidates(status);
create index if not exists event_candidates_fingerprint_idx on public.event_candidates(fingerprint);

create table if not exists public.event_opportunities (
  id bigint generated by default as identity primary key,
  candidate_id bigint references public.event_candidates(id) on delete set null,
  source_table text,
  source_key text,
  name text not null,
  start_date date,
  end_date date,
  city text,
  country text,
  url text,
  owner_person text not null,
  opportunity_type text not null check (opportunity_type in ('apply','organizer_outreach','attend_for_buyers','exploit_existing_trip','monitor_specific_opening','partner')),
  queue_stage text not null default 'watchlist' check (queue_stage in ('apply_now','reach_out','along_the_route','conflicts','watchlist','partner_opportunities','retired')),
  opportunity_score numeric(5,2),
  priority text check (priority in ('High','Medium','Low')),
  next_action text,
  next_action_due date,
  rationale text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_table, source_key, owner_person)
);
create index if not exists event_opportunities_queue_idx on public.event_opportunities(queue_stage, opportunity_score desc);
create index if not exists event_opportunities_owner_idx on public.event_opportunities(owner_person, opportunity_score desc);

create table if not exists public.person_event_fit (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.event_opportunities(id) on delete cascade,
  person_key text not null,
  commercial_fit smallint not null default 0 check (commercial_fit between 0 and 100),
  persona_fit smallint not null default 0 check (persona_fit between 0 and 100),
  access_fit smallint not null default 0 check (access_fit between 0 and 100),
  logistics_fit smallint not null default 0 check (logistics_fit between 0 and 100),
  strategic_signal smallint not null default 0 check (strategic_signal between 0 and 100),
  total_score numeric(5,2),
  logistics_status text not null default 'unknown' check (logistics_status in ('already_nearby','nearby_trip','requires_new_trip','geographic_conflict','unknown')),
  calendar_location text,
  calendar_location_source text,
  default_base_used boolean not null default false,
  overlap_note text,
  hard_conflict boolean not null default false,
  scoring_reason jsonb not null default '{}'::jsonb,
  evaluated_at timestamptz not null default now(),
  unique(opportunity_id, person_key)
);

create table if not exists public.travel_windows (
  id bigint generated by default as identity primary key,
  person_key text not null,
  start_date date not null,
  end_date date not null,
  city text,
  country text,
  region text,
  source text not null default 'calendar',
  source_event_id text,
  confidence text not null default 'confirmed' check (confidence in ('confirmed','likely','default_base')),
  notes text,
  created_at timestamptz not null default now(),
  unique(person_key,start_date,end_date,city,country,source_event_id)
);
create index if not exists travel_windows_person_dates_idx on public.travel_windows(person_key,start_date,end_date);

create table if not exists public.target_accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  industry text,
  region text,
  priority text check (priority in ('A','B','C')),
  owner_person text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.event_people (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.event_opportunities(id) on delete cascade,
  full_name text not null,
  title text,
  company text,
  person_type text not null default 'speaker' check (person_type in ('speaker','attendee','organizer','sponsor','target')),
  target_account_id bigint references public.target_accounts(id) on delete set null,
  linkedin_url text,
  source_url text,
  relevance_reason text,
  created_at timestamptz not null default now(),
  unique(opportunity_id, full_name, company, person_type)
);

create table if not exists public.event_contacts (
  id bigint generated by default as identity primary key,
  opportunity_id bigint not null references public.event_opportunities(id) on delete cascade,
  full_name text,
  role text,
  organization text,
  email text,
  linkedin_url text,
  contact_type text not null default 'program' check (contact_type in ('program','speaker_team','partnerships','organizer','warm_intro','other')),
  source_url text,
  confidence text check (confidence in ('verified','probable','unknown')),
  warm_via text,
  owner_person text,
  outreach_status text not null default 'not_started' check (outreach_status in ('not_started','drafted','contacted','followed_up','replied','meeting','closed')),
  last_contacted_at timestamptz,
  next_follow_up_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.event_postmortems (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_key text not null,
  person_key text,
  speaking_achieved boolean,
  senior_buyer_conversations integer,
  qualified_leads integer,
  follow_up_meetings integer,
  useful_partnerships integer,
  estimated_trip_cost numeric(12,2),
  would_attend_again text check (would_attend_again in ('definitely','probably','probably_not','definitely_not')),
  why text,
  completed_by text,
  completed_at timestamptz not null default now(),
  unique(source_table,source_key,person_key)
);

-- Updated-at helper for opportunities only.
create or replace function public.touch_event_opportunity_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists trg_touch_event_opportunity_updated_at on public.event_opportunities;
create trigger trg_touch_event_opportunity_updated_at
before update on public.event_opportunities
for each row execute function public.touch_event_opportunity_updated_at();
