const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');
const C=require('../src/booking-core.js');const now='2026-09-10';
const base={name:'Buyer forum',start_date:'2026-10-01',end_date:'2026-10-02',location:'Munich, Germany',booking:{}};
const normalize=r=>C.normalize({...base,...r},null,now);
assert.equal(C.day('2026-02-30'),'');assert.equal(C.day('2028-02-29'),'2028-02-29');
assert.equal(C.safeUrl('javascript:alert(1)'),'');
assert.equal(normalize({}).q.score,null);
assert.equal(normalize({}).active,false);
const b={action:'Apply',owner:'Thor',next_action:'Submit proposal',due:'2026-09-15',reason:'Earned stage for healthcare buyers'};
const active=normalize({booking:b});assert.equal(active.active,true);
assert.equal(C.groups([active],now).applications.length,1);
assert.equal(normalize({booking:{...b,owner:''}}).active,false);
const snooze=normalize({booking:{...b,recheck_on:'2026-09-20',recheck_trigger:'CFP opens'}});
assert.equal(snooze.active,false);assert.equal(C.groups([snooze],now).decisions.length,0);
assert.equal(normalize({booking:{recheck_on:now}}).needsDecision,true);
assert.equal(normalize({booking:{...b,action:'Pass'}}).active,false);
assert.equal(normalize({end_date:'2026-09-09',booking:b}).active,false);
assert.equal(normalize({hidden:true,booking:b}).active,false);
assert.equal(normalize({booking:{...b,completed_at:now}}).active,false);
const submitted=normalize({submitted_at:'2026-09-01'});
assert.equal(C.groups([submitted],now).followups.length,1);
assert.equal(C.groups([normalize({submitted_at:'2026-09-01',booking:{organizer_reply_at:now}})],now).followups.length,0);
const evidence=[{kind:'end_user_speakers',url:'https://example.com/speakers',checked:now,note:'Published end-user speakers'}, {kind:'audience_breakdown',url:'https://example.com/audience',checked:now,note:'Published job titles'}];
const qualified=normalize({booking:{buyer_fit:'strong',evidence}});assert.equal(qualified.q.score,50);assert.equal(qualified.q.strong,true);
assert.equal(normalize({booking:{evidence:[...evidence,...evidence]}}).q.score,50);
assert.equal(normalize({booking:{evidence:[{...evidence[0],checked:'2024-01-01'}]}}).q.score,null);
assert.equal(normalize({booking:{evidence:[{...evidence[0],url:'javascript:bad'}]}}).q.score,null);
assert.equal(normalize({name:'Chief AI Officer Summit Boston 2026'}).q.excluded,true);
const m=C.metrics([submitted,normalize({status_tags:['Booked'],booking:{meetings_booked:3,qualified_opportunities:1}})]);
assert.deepEqual(m,{applications:1,replies:0,slots:1,meetings:3,attended:0,opportunities:1,trips:0});
assert.equal(C.sameCity('Munich, Germany','Munich'),true);assert.equal(C.sameCity('London','Munich'),false);assert.equal(C.sameCity('New York','NYC'),true);assert.equal(C.sameCity('TBD','TBD'),false);
const pack=C.tripPack({start_date:'2026-09-28',end_date:'2026-09-30',city:'Munich'},[qualified,normalize({location:'London, UK'})],[{name:'Buyer',city:'Munich'}]);
assert.equal(pack.nearby.length,1);assert.equal(pack.targets.length,1);
assert.equal(C.tripPack({start_date:'2026-11-01',end_date:'2026-11-03',city:'Munich'},[qualified],[]).nearby.length,0);
// Parse every executable script emitted by the Python f-string generator.
const html=fs.readFileSync('public/index.html','utf8');let count=0;
for(const match of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)){if(/application\/json|src=/.test(match[1]))continue;new vm.Script(match[2]);count++;}
assert.ok(count>=2);assert.ok(html.includes('id="ops-action"'));assert.ok(html.includes("setView(VIEW_NAMES.indexOf(requested) !== -1 ? requested : 'action')"));
const routes=JSON.parse(fs.readFileSync('vercel.json'));assert.equal(routes.redirects.find(r=>r.source==='/').destination,'/events');assert.equal(routes.rewrites.find(r=>r.source==='/events').destination,'/index.html');
console.log('Booking rules, evidence, outcomes, trip matching, routing and '+count+' generated scripts passed.');
